#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PUBLIC_ORIGIN="https://hsmjobs.musavvir.work"
PUBLIC_HOST="hsmjobs.musavvir.work"
ZONE_HOST="musavvir.work"
WORKER_NAME="hsm-jobs-mcp"
D1_NAME="hsm-jobs-index"
D1_BINDING="JOBS_INDEX"
WRANGLER_CONFIG="wrangler.jsonc"
PLACEHOLDER_D1_ID="00000000-0000-0000-0000-000000000001"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

_require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    warn "missing required command: $1"
    exit 1
  }
}

_wrangler() {
  if [[ -x "$REPO_ROOT/node_modules/.bin/wrangler" ]]; then
    "$REPO_ROOT/node_modules/.bin/wrangler" "$@"
  else
    npx wrangler "$@"
  fi
}

# Patch database_id in wrangler.jsonc (keeps the comment; JSONC-safe replace).
_set_wrangler_database_id() {
  local id="$1"
  local tmp
  tmp=$(mktemp)
  sed -E "s/\"database_id\": \"[^\"]+\"/\"database_id\": \"${id}\"/" \
    "$WRANGLER_CONFIG" > "$tmp"
  mv "$tmp" "$WRANGLER_CONFIG"
  printf '  %s✓ wrote%s database_id → %s\n' "$GREEN" "$RESET" "$WRANGLER_CONFIG"
}

# Ensure custom_domain route for PUBLIC_HOST exists in wrangler.jsonc.
_ensure_custom_domain_route() {
  if grep -q "\"pattern\": \"${PUBLIC_HOST}\"" "$WRANGLER_CONFIG"; then
    note "custom domain route already present in $WRANGLER_CONFIG"
    return 0
  fi
  local tmp
  tmp=$(mktemp)
  # Use [[:space:]] (POSIX) — macOS awk does not treat \s as whitespace.
  awk -v host="$PUBLIC_HOST" '
    BEGIN { inserted = 0 }
    /^[[:space:]]*"d1_databases"/ && !inserted {
      print "  \"routes\": ["
      print "    {"
      print "      \"pattern\": \"" host "\","
      print "      \"custom_domain\": true"
      print "    }"
      print "  ],"
      inserted = 1
    }
    { print }
    END {
      if (!inserted) {
        print "ERROR: could not find d1_databases key to insert routes before" > "/dev/stderr"
        exit 1
      }
    }
  ' "$WRANGLER_CONFIG" > "$tmp"
  mv "$tmp" "$WRANGLER_CONFIG"
  if ! grep -q "\"pattern\": \"${PUBLIC_HOST}\"" "$WRANGLER_CONFIG"; then
    warn "failed to write custom domain route into $WRANGLER_CONFIG"
    return 1
  fi
  printf '  %s✓ added%s custom domain route for %s\n' "$GREEN" "$RESET" "$PUBLIC_HOST"
}

_extract_database_id() {
  # Prefer JSON-ish "database_id": "uuid" from wrangler output.
  printf '%s' "$1" | grep -Eo '"database_id"[[:space:]]*:[[:space:]]*"[0-9a-fA-F-]{36}"' \
    | head -n1 | grep -Eo '[0-9a-fA-F-]{36}' || true
}

_require_cmd node
_require_cmd npm
_require_cmd curl
_require_cmd sed
_require_cmd awk
_require_cmd grep

if [[ ! -d node_modules ]]; then
  printf 'Installing npm dependencies (one-time)…\n'
  npm install
fi

banner "hsm-jobs-mcp · Cloudflare bootstrap"

# ── 1. Confirm origin and DNS zone ────────────────────────────────────────
stage "Confirm origin and DNS zone"
say "This wires the locked public origin to Cloudflare Workers + one D1 jobs index."
say "No second local-only store. No product auth / rate limits / paid tier."
note "Origin: $PUBLIC_ORIGIN"
note "Zone that must already live in your Cloudflare account: $ZONE_HOST"
open_url "https://dash.cloudflare.com/"
step "Log in if needed."
step "Open the zone list and confirm $ZONE_HOST is an Active zone on this account."
step "If the zone is missing, add $ZONE_HOST first (or move DNS to Cloudflare), then re-run."
pause "Press Enter when $ZONE_HOST is Active on this Cloudflare account."
write_env PUBLIC_ORIGIN "$PUBLIC_ORIGIN"

# ── 2. Wrangler login + account id ────────────────────────────────────────
stage "Wrangler login"
say "Wrangler needs a browser login so later CLI steps can create D1 and deploy."
step "A browser window will open for Cloudflare OAuth. Approve access."
if confirm "Run wrangler login now?"; then
  _wrangler login || warn "wrangler login exited non-zero; continue only if you are already logged in"
else
  note "Skipped login — assuming you already ran: npx wrangler login"
fi
say "Grab your Account ID from the dashboard overview (right sidebar) or Workers overview."
open_url "https://dash.cloudflare.com/"
step "Click into your account → copy Account ID (32 hex chars)."
ask CLOUDFLARE_ACCOUNT_ID "Paste Cloudflare Account ID:"
[[ -n "$CLOUDFLARE_ACCOUNT_ID" ]] || { warn "Account ID is required"; exit 1; }
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
export CLOUDFLARE_ACCOUNT_ID

# ── 3. Create D1 (or reuse) ───────────────────────────────────────────────
stage "Create D1 jobs index"
say "Create remote D1 database '$D1_NAME' (Western Europe). Same schema as local wrangler."
existing_id="$(_existing D1_DATABASE_ID || true)"
if [[ -n "$existing_id" && "$existing_id" != "$PLACEHOLDER_D1_ID" ]]; then
  note "Found existing D1_DATABASE_ID in .env: $existing_id"
  if confirm "Reuse that database id?"; then
    D1_DATABASE_ID="$existing_id"
  else
    D1_DATABASE_ID=""
  fi
fi
if [[ -z "${D1_DATABASE_ID:-}" ]]; then
  if confirm "Create a new D1 database named $D1_NAME now?"; then
    say "Running: wrangler d1 create $D1_NAME --location=weur"
    create_out="$(_wrangler d1 create "$D1_NAME" --location=weur 2>&1 || true)"
    printf '%s\n' "$create_out" | sed 's/^/  /'
    D1_DATABASE_ID="$(_extract_database_id "$create_out")"
    if [[ -z "$D1_DATABASE_ID" ]]; then
      warn "Could not parse database_id from create output (name may already exist)."
      say "Listing remote D1 databases — find $D1_NAME and copy its UUID."
      _wrangler d1 list 2>&1 | sed 's/^/  /' || true
      ask D1_DATABASE_ID "Paste the database_id UUID for $D1_NAME:"
    fi
  else
    say "Listing remote D1 databases so you can paste an existing id."
    _wrangler d1 list 2>&1 | sed 's/^/  /' || true
    ask D1_DATABASE_ID "Paste the database_id UUID for $D1_NAME:"
  fi
fi
[[ -n "$D1_DATABASE_ID" ]] || { warn "database_id is required"; exit 1; }
[[ "$D1_DATABASE_ID" =~ ^[0-9a-fA-F-]{36}$ ]] || {
  warn "database_id does not look like a UUID: $D1_DATABASE_ID"
  exit 1
}
write_env D1_DATABASE_ID "$D1_DATABASE_ID"
_set_wrangler_database_id "$D1_DATABASE_ID"
note "Binding stays $D1_BINDING → env.JOBS_INDEX (unchanged)."

# ── 4. Apply remote migrations ────────────────────────────────────────────
stage "Apply remote D1 migrations"
say "Apply migrations/ to the remote jobs index so shared and private use one schema."
if confirm "Apply remote migrations now?"; then
  _wrangler d1 migrations apply "$D1_NAME" --remote
  printf '  %s✓ remote migrations applied%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("remote D1 migrations (run: npx wrangler d1 migrations apply $D1_NAME --remote)")
  warn "skipped migrations — deploy may boot against an empty/unmigrated DB"
fi

# ── 5. Custom domain in wrangler config ───────────────────────────────────
stage "Attach custom domain in config"
say "Cloudflare will create DNS + TLS for $PUBLIC_HOST when we deploy."
say "Prerequisite (already confirmed): zone $ZONE_HOST is Active on this account."
note "If an old CNAME already exists for $PUBLIC_HOST, delete it in DNS first."
open_url "https://dash.cloudflare.com/"
step "Optional: open $ZONE_HOST → DNS → Records and remove any existing $PUBLIC_HOST CNAME."
pause "Press Enter when DNS is clear (or you confirmed no conflicting record)."
_ensure_custom_domain_route

# ── 6. Deploy Worker ──────────────────────────────────────────────────────
stage "Deploy Worker"
say "Publish $WORKER_NAME and attach $PUBLIC_HOST."
if confirm "Run wrangler deploy now?"; then
  _wrangler deploy
  printf '  %s✓ deploy finished%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("wrangler deploy")
  warn "skipped deploy"
fi

# ── 7. Operator API token (optional secret) ───────────────────────────────
stage "Operator API token (optional)"
say "v1 has no Worker auth. This token is only for you (and later CI) to run wrangler without a browser."
say "Skip if you only use wrangler login on this machine."
if confirm "Create and save a Cloudflare API token?"; then
  open_url "https://dash.cloudflare.com/profile/api-tokens"
  step "Create Token → start from 'Edit Cloudflare Workers' (or custom with Workers + D1 edit)."
  step "Include this account and zone $ZONE_HOST."
  step "Create token → copy it once (Cloudflare will not show it again)."
  ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
  if [[ -n "$CLOUDFLARE_API_TOKEN" ]]; then
    write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
    note "Stored in .env only (gitignored). No GitHub Actions workflow references this yet."
  else
    note "Empty token — nothing written."
  fi
else
  note "Skipped API token."
fi

# ── 8. Verify /health and /mcp ────────────────────────────────────────────
stage "Verify public origin"
say "Checking $PUBLIC_ORIGIN/health and an MCP initialize on $PUBLIC_ORIGIN/mcp …"
health_code="$(curl -sS -o /tmp/hsm-jobs-health.body -w '%{http_code}' "$PUBLIC_ORIGIN/health" || true)"
mcp_code="$(curl -sS -o /tmp/hsm-jobs-mcp.body -w '%{http_code}' \
  -X POST "$PUBLIC_ORIGIN/mcp" \
  -H 'accept: application/json, text/event-stream' \
  -H 'content-type: application/json' \
  --data '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"bootstrap-wizard","version":"0.0.1"}}}' \
  || true)"
note "/health → HTTP $health_code"
note "/mcp initialize → HTTP $mcp_code"
if [[ "$health_code" == "200" ]]; then
  printf '  %s✓ /health reachable%s\n' "$GREEN" "$RESET"
  sed 's/^/  /' /tmp/hsm-jobs-health.body 2>/dev/null || true
  printf '\n'
else
  warn "/health not OK yet (got $health_code)."
  SKIPPED+=("fix /health on $PUBLIC_ORIGIN (DNS/TLS may still be propagating; curl -i $PUBLIC_ORIGIN/health)")
fi
if [[ "$mcp_code" =~ ^2 ]]; then
  printf '  %s✓ /mcp initialize OK%s\n' "$GREEN" "$RESET"
  if grep -q 'hsm-jobs-mcp' /tmp/hsm-jobs-mcp.body 2>/dev/null; then
    note "serverInfo.name looks like hsm-jobs-mcp"
  else
    warn "response body did not clearly contain hsm-jobs-mcp — open the body if unsure"
    sed 's/^/  /' /tmp/hsm-jobs-mcp.body 2>/dev/null | head -n 20 || true
  fi
else
  warn "/mcp initialize failed (got '$mcp_code')."
  SKIPPED+=("fix /mcp initialize on $PUBLIC_ORIGIN")
fi
rm -f /tmp/hsm-jobs-health.body /tmp/hsm-jobs-mcp.body

finish
say "Locked origin: $PUBLIC_ORIGIN"
say "Re-run anytime: ./scripts/cloudflare-bootstrap.sh"
say "Private path stays the same stack: npm run dev (wrangler + D1)."
